1. Спершу я виконала усі базові приклади у файлі app.py, який я прикріпила у репозиторій
2. Результат виконання команди python .

We are in the __main__
2020-11-07 20:37:08.408498
linux
3. Результат виконання команди  python . -h
usage: . [-h] [-o OPT] [-l]

Приклад передачі аргументів у Python програму.

optional arguments:
  -h, --help            show this help message and exit
  -o OPT, --optional OPT
                        Цей параметр є вибірковим.
  -l, --logs            Якщо виконати команду з цим параметром будуть
                        виводитись логи.

4. Передавши python . наступний аргумент отримуємо додаткове повідомлення від програми :

З консолі було передано аргумент
 ========== >> Цей текст також має вивестись << ==========

5. Запустивши з консолі python . --logs були виведені усі логи, які були можливими та прописаними у самій програмі.

2020-11-07 20:46:06,187 root INFO: Тут буде просто інформативне повідомлення
2020-11-07 20:46:06,187 root WARNING: Це Warning повідомлення
2020-11-07 20:46:06,187 root ERROR: Це повідомлення про помилку

6. Створила функцію в common.py :
 def funct(x):
	if x:
		a=[i for i in range (0,101) if i%2==0 ]
		print(a)
	else:
		a=[i for i in range(1,100) if i%2==1]
		print(a)
funct(False)

Її вивід: 
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]

7. Створила функцію з помилкою, у випадку її виникнення виводиться повідомлення про помилку за допомогою логування.
def func(a=True):
	number1=0
	number2=15
	try:
	   print("Поділимо 15 на 0, у результаті отримаємо: ",number2/number1)

	except ZeroDivisionError:
		logger.error("Це повідомлення про помилку")
		print("Помилка")
	else:
		logger.info("Тут буде просто інформативне повідомлення")

	finally:
		print("На нуль ділити не можна!!!")


